Repository thoth-station/prescriptions-gh-release-notes-job, pull requests merged in 2021-05, with the labels that each got.

#3 Initial project import
  .aicoe-ci.yaml
  CHANGELOG.md
  OWNERS_ALIASES
  Pipfile
  Pipfile.lock
  README.md
  README.rst
  app.py
  pyproject.toml
  template/__init__.py
  template/version.py
Labels: approved, size/XXL

#8 Use Python 3.8
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#12 Provide default log level
  app.py
Labels: approved, size/XS

#14 Add API version and header of prescription file
  app.py
Labels: approved, size/S

#15 update the prow resource limits
  .prow.yaml
Labels: approved, size/XS
